from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

# Remove the inner lists
stringg = ["áo rất đẹp", "áo quá xấu áo khác hình ", "áo hơi đắt nhưng áo rất đẹp"]


tfidf_value = tfidf.fit_transform(stringg).toarray()

print(tfidf_value)
import re

patterns = {
 r'\bmn\b': 'mọi người',
    r'\bsp\b': 'sản phẩm',
    r'\bđc\b': 'được',
    r'\bnhah\b': 'nhanh',
    r'\bhong\b': 'không',
    r'\bk\b': 'không',
    r'\bthui\b': 'thôi',
    r'\be\b': 'em',
    r'\bgh\b': 'giao hàng',
    r'\bnhư v\b': 'như vậy',
    r'\btr\b': 'trời',
    r'\bon\b': 'ổn',
    r'\bnma\b': 'nhưng mà',
    r'\bnm\b': 'nhưng mà',
    r'\bkhéc\b': 'khét',
    r'\bhih\b': 'hình',
    r'\bqc\b': 'quảng cáo',
    r'\bt2\b': 'thứ hai',
    r'\bsd\b': 'sử dụng',
    r'\bhcm\b': 'hồ chí minh',
    r'\bhn\b': 'hà nội',
    r'\bcmt\b': 'comment',
    r'\bng\b': 'người',
    r'\bsr\b': 'xin lỗi',
    r'\blg\b': 'lượng',
    r'\bhsd\b': 'hạn sử dụng',
    r'\bhok\b': 'không',
    r'\bh\b': 'giờ',
    r'\bae\b': 'anh em',
    r'\bnt\b': 'nhắn tin',
    r'\bsop\b': 'shop',
    r'\bln\b': 'luôn',
    r'\btrc\b': 'trước',
    r'\bthik\b': 'thích',
    r'\bmk\b': 'mình',
    r'\bsx\b': 'sản xuất',
    r'\bnhug\b': 'nhưng',
    r'\bsl\b': 'số lượng',
    r'\bthank\b': 'cảm ơn',
    r'\bthanks\b': 'cảm ơn',
    r'\bnka\b': 'nha',
    r'\bthowm\b': 'thơm',
    r'\bchuwa\b': 'chưa',
    r'\bbic\b': 'biết',
    r'\btn\b': 'tin nhắn',
    r'\bđươcj\b': 'được',
    r'\bvs\b': 'với',
    r'\bdk\b': 'được',
    r'\br\b': 'rồi',
    r'\bmjh\b': 'mình',
    r'\bntn\b': 'như thế nào',
    r'\bbit\b': 'biết',
    r'\bkm\b': 'khuyến mãi',
    r'\bmng\b': 'mọi người',
    r'\bcx\b': 'cũng',
    r'\btt\b': 'tiếp tục',
    r'\bcl\b': 'chất lượng',
    r'\bktra\b': 'kiểm tra',
    r'\bktr\b': 'kiểm tra',
    r'\bz\b': 'vậy',
    r'\bb\b': 'bạn',
    r'\kbt\b': 'không biết',
    r'\bj\b': 'gì',
    r'\bđt\b': 'điện thoại',
    r'\blụong\b': 'lượng',
    r'\bkaij\b': 'lại',
    r'\bhk\b': 'không',
    r'\bko\b': 'không',
    r'\bđưj\b': 'được',
    r'\bbidy\b': 'body',
    r'\boki\b': 'ok',
    r'\bnv\b': 'nhân viên',
    r'\bchx\b': 'chưa',
    r'\bbt\b': 'biết',
    r'\bnhm\b': 'nhưng mà',
    r'\bwa\b': 'quá',
    r'\bchâm\b': 'chậm',
    r'\bkhum\b': 'không',
    r'\bchac\b': 'chắc',
    r'\bcjhâm\b': 'chậm',
    r'\bahop\b': 'shop',
    r'\bxme\b': 'xem',
    r'\bđnahs\b': 'đánh',
    r'\bnghũ\b': 'nghĩ',
    r'\btrỏng\b': 'trong',
    r'\bokela\b': 'ok',
    r'\btks\b': 'cảm ơn',
    r'\bcùa\b': 'của',
    r'\bơt\b': 'ở',
    r'\bksao\b': 'không sao',
    r'\bokelah\b': 'ok',
    r'\bmụi\b': 'mọi',
    r'\bngừoi\b': 'người',
    r'\bmac\b': 'mác',
    r'\bhfgng\b': 'hàng',
    r'\bgg\b': 'giảm giá',
    r'\bap\b': 'áp',
    r'\bdc\b': 'được',
    r'\bmag\b': 'mang',
    r'\bbs\b': 'bác sĩ',
    r'\bthươgf\b': 'thường',
    r'\btu van\b': 'tư vấn',
    r'\btgian\b': 'thời gian',
    r'\bch\b': 'chưa',
    r'\btg\b': 'thời gian',
    r'\bcbi\b': 'chuẩn bị',
    r'\bngưồi\b': 'người',
    r'\bnhê\b': 'nha',
    r'\bni\b': 'này',
    r'\b\fai\b': "phải",
     r'\b\ship pơ\b': "shipper",
    r'\bhiêun\b': 'hiệu',
    r'\btố\b': 'tốt',
    r'\btuýt\b': 'tuýp',
    r'\bnx\b': 'nữa',
    r'\btw\b': 'trung ương',
    r'\blm\b': 'làm',
    r'\bqq\b': 'quần què',
    r'\bzire\b': 'size',
    r'\bđâh\b': 'đâu',
    r'\blun\b': 'luôn',
    r'\bphake\b': 'fake',
    r'\blonn\b': 'lol',
    r'\bchổ\b': 'chỗ',
    r'\bquâ\b': 'quá',
    r'\bsít\b': 'shit',
    r'\bdb\b': 'đầu_buồi',
    r'\bchày\b': 'trầy',
    r'\bqa\b': 'quá',
    r'\bns\b': 'nó',
    r'\bbôg\b': 'bông',
    r'\bxâu\b': 'xấu',
    r'\blh\b': 'liên hệ',
    r'\bll\b': 'liên lạc',
    r'\bgioa\b': 'giao',
    r'\bnheng\b': 'nhưng',
    r'\bak\b': 'á',
    r'\bphẩn\b': 'phẩm',
    r'\bcám\b': 'cảm',
    r'\bah\b': 'á',
    r'\bokey\b': 'ok',
    r'\blứm\b': 'lắm',
    r'\btoẹt\b': 'tuyệt',
    r'\bkím\b': 'kiếm',
    r'\bgood\b': 'tốt',
    r'\btq\b': 'trung quốc',
    r'\btiệc vời\b': 'tuyệt vời',
    r'\bcunhx\b': 'cũng',
    r'\bm\b': 'mình',
    r'\bspham\b': 'sản phẩm',
    r'\bks\b': 'không sao',
    r'\btieenf\b': 'tiền',
    r'\bqt\b': 'quốc tế',
    r'\bnhunge\b': 'nhưng',
    r'\bphaamf\b': 'phẩm',
    r'\bbk\b': 'biết',
    r'\bcos\b': 'có',
    r'\btot\b': 'tốt',
    r'\bkh\b': 'khách hàng',
    r'\bnod\b': 'nó',
    r'\brui\b': 'rồi',
    r'\btrk\b': 'trước',
    r'\bkg\b': 'không',
    r'\bđx\b': 'được',
    r'\bđưocj\b': 'được',
    r'\blzd\b': 'lazada',
    r'\bshipper\b': 'shiper',
    r'\bnhưnh\b': 'nhưng',
    r'\bnhung\b': 'nhưng',
    r'\bokie\b': 'ok',
    r'\bb\b': 'bạn',
    r'\bph\b': 'phẩm',
    r'\bsez\b': 'sẽ',
    r'\bđng\b': 'đóng',
    r'\bcb\b': 'chuẩn bị',
    r'\bđươ\b': 'được',
    r'\blượg\b': 'lượng',
    r'\bđươc\b': 'được',
    r'\batvs\b': 'an toàn vệ sinh',
    r'\bgđ\b': 'gia đình',
    r'\btc\b': 'tính chất',
    r'\bđonga\b': 'đóng',
    r'\bđings\b': 'đóng',
    r'\bnhueng\b': 'nhưng',
    r'\bre\b': 'rẻ',
    r'\brats\b': 'rất',
    r'\btyueet\b': 'tuyệt',
    r'\bđưôcj\b': 'được',
    r'\bqả\b': 'quả',
    r'\bddep\b': 'đẹp',
    r'\bkl\b': 'không',
    r'\bnnao\b': 'như nào',
    r'\bhủ\b': 'hũ',
    r'\b\n\b': " ",
    r'\b\bt\b': "bình thường",
    r'\b\bth\b': "bình thường",
    r'\b\bthg\b': "bình thường",

}

# Remove the \b\b from patterns
cleaned_patterns = {re.sub(r'\\b', '', key): value for key, value in patterns.items()}

# Print cleaned patterns
for key, value in cleaned_patterns.items():
    print(f'{key}: {value}')
